### ISSUE TITLE
How to get mAP by your code?

### ISSUE THREAD

**Issue by juipengchang** [sming256/TSI#2]

**Comment by juipengchang** [comment]
> _No description provided._

**Comment by sming256** [comment]
In the post-processing, we evaluate the AUC and mAP by default. You can also check the mAP results from provided google drive folder. 
Noted that TSI mainly focuses on the diversity of different scales of actions, so the proposal generation ability, which is measured by AUC,  surpasses the baseline BMN. However, we find that the mAP is not as good as BMN, since the top1 and top5 recall are lower. This is in our expectation and we have mentioned this in Section 5.3 in the paper.
