### ISSUE TITLE
About uNet_test.npy

### ISSUE THREAD

**Issue by juipengchang** [sming256/TSI#3]
Thinks for reply! I got mAP for THUMOS14 now. Actually I am using your model for a new data set but there is no _uNet_test.npy_ for my data set. Could you tell me what is this file and how to get it for a new data set? Think you!

**Comment by sming256** [comment]
`uNet_test.npy` is the video-level classification result of THUMOS14. Since TSI is a proposal generation method, it does not predict the action class for each proposal. 

For your own dataset, (1) if each video has only one action class, you can use a standard action recognition model to acquire video-level classification results, then fuse this with TSI. (2) if each video has different classes of action instances, you can use another proposal refinement network that can use the action proposals generated by TSI as the input, to classify the actions, such as P-GCN.
